apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3api.fullname" . }}-secret
  labels:
  {{- include "s3api.labels" . | nindent 4 }}
stringData:
  AWS_ACCESS_KEY_ID: {{ required "secret.awsAccessKeyId is required" .Values.secret.awsAccessKeyId
    | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "secret.awsSecretAccessKey is required" .Values.secret.awsSecretAccessKey
    | quote }}
  SECRET_KEY: {{ required "secret.secretKey is required" .Values.secret.secretKey
    | quote }}
type: Opaque